//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IsporukaMunicije
    {
        [Required(ErrorMessage = "Polje je obavezno.")]
        public int BrojFakture { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public System.DateTime VremeIsporuke { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public double cena { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string ImeKupca { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string PrezimeKupca { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string AdresaKupca { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string BrojTelefonaKupca { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string JMBG { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public int IDMunicije { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string statusIsporuke { get; set; }
    }
}
