//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekat.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KupovinaMunicije
    {
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string Adresa { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string BrojTelefona { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string BrojKartice { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string PINKartice { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public string JMBG { get; set; }
        [Required(ErrorMessage = "Polje je obavezno.")]
        public int IDMunicije { get; set; }
    }
}
